input_img_num: 5
batch_size: 1
data_path: /home/B_UserData/dongzhipeng/Datasets/SV-UDIS-D/  # 数据集根路径
sub_datasets:  # 子数据集名称
  # - RealTractor5
  # - RealTractor6
  - UDIS
  # - WhiteCar
model: warp.pth  # MODEL_DIR 下的模型文件
net_input_width: 512
net_input_height: 512
use_warp: False
warp_cfg:  # if use_warp == True
  warp_mode: cylindrical  # cylindrical, spherical
  scale: 720
use_loader_data_aug: False  # 加载数据时进行数据增广，包括滑动窗口平移、左右顺序反转，在CPU上处理